import { useEffect, useRef, useState } from 'react';
import { ZoomIn, ZoomOut, RefreshCw, ExternalLink, AlertTriangle, Info, Download } from 'lucide-react';
import { Plan } from '@/types';
import { cn } from '@/lib/utils';
import { toast } from 'sonner';

interface Props {
  plan: Plan;
  onRegenerate: (feedback: string) => Promise<void>;
  regenerationsLeft: number;
}

export function ArchitectureTab({ plan, onRegenerate, regenerationsLeft }: Props) {
  const mermaidRef = useRef<HTMLDivElement>(null);
  const [zoom, setZoom] = useState(1);
  const [feedback, setFeedback] = useState('');
  const [showFb, setShowFb] = useState(false);
  const [regen, setRegen] = useState(false);
  const [editMode, setEditMode] = useState(false);
  const [rawSyntax, setRawSyntax] = useState(plan.architectureDiagram);
  const [syntaxError, setSyntaxError] = useState('');

  const renderDiagram = async (syntax: string) => {
    if (!mermaidRef.current) return;
    // Trim leading whitespace from each line so Mermaid parses correctly
    const cleaned = syntax
      .split('\n')
      .map(line => line.trimStart())
      .join('\n')
      .trim();
    try {
      const mermaid = (await import('mermaid')).default;
      mermaid.initialize({
        startOnLoad: false,
        securityLevel: 'loose',
        theme: 'dark',
        themeVariables: {
          primaryColor: 'var(--bg-elevated)',
          primaryTextColor: 'var(--text-primary)',
          primaryBorderColor: 'var(--border)',
          lineColor: 'var(--text-muted)',
          background: 'var(--bg)',
          mainBkg: 'var(--bg-panel)',
          fontFamily: 'Inter, sans-serif',
          fontSize: '13px',
        },
      });
      mermaidRef.current.innerHTML = '';
      const id = 'mermaid-' + Date.now();
      const { svg } = await mermaid.render(id, cleaned);
      mermaidRef.current.innerHTML = svg;
      setSyntaxError('');
    } catch (e: any) {
      setSyntaxError(String(e?.message ?? 'Syntax error'));
      if (mermaidRef.current) mermaidRef.current.innerHTML = '';
    }
  };

  useEffect(() => { setRawSyntax(plan.architectureDiagram); }, [plan.architectureDiagram]);
  useEffect(() => { renderDiagram(rawSyntax); }, [rawSyntax]);

  const handleRegenerate = async () => {
    if (regenerationsLeft <= 0) { toast.error('Max regenerations reached'); return; }
    setRegen(true);
    await onRegenerate(feedback);
    setFeedback(''); setShowFb(false); setRegen(false);
  };

  const exportSyntax = () => {
    const blob = new Blob([rawSyntax], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url; a.download = 'architecture.mmd'; a.click();
    URL.revokeObjectURL(url);
    toast.success('Diagram exported');
  };

  return (
    <div className="p-7 space-y-6 max-w-5xl mx-auto">
      {/* Header */}
      <div className="flex items-start justify-between fade-up">
        <div>
          <h2 className="text-2xl font-black tracking-tighter text-[var(--text-primary)]">Architecture</h2>
          <p className="text-[var(--text-muted)] text-sm mt-0.5">System diagram generated by HackPilot Agent</p>
        </div>
        <div className="flex items-center gap-2">
          <span className="text-[10px] font-mono text-[var(--text-muted)] bg-[var(--bg-elevated)]
            border border-[var(--border)] px-2 py-1 rounded-lg">
            {regenerationsLeft} regen left
          </span>
          <button onClick={exportSyntax}
            className="btn-secondary px-3 py-2 text-sm">
            <Download size={13} /> Export
          </button>
          <button onClick={() => setShowFb(s => !s)} disabled={regenerationsLeft <= 0}
            className={cn('flex items-center gap-1.5 px-3 py-2 rounded-lg text-sm font-medium transition-all',
              regenerationsLeft > 0
                ? 'btn-primary py-2 px-3'
                : 'bg-[var(--bg-elevated)] text-[var(--text-muted)] border border-[var(--border)] cursor-not-allowed')}>
            <RefreshCw size={13} className={regen ? 'animate-spin' : ''} />
            Regenerate
          </button>
        </div>
      </div>

      {/* Banners */}
      {plan.priorArt.found && plan.priorArt.matches.length > 0 && (
        <div className="flex gap-3 p-4 rounded-xl border border-amber-500/20 bg-amber-500/5 fade-up-1">
          <AlertTriangle size={16} className="text-amber-400 shrink-0 mt-0.5" />
          <div>
            <p className="text-amber-300 font-semibold text-sm">Similar projects found</p>
            <div className="space-y-1.5 mt-2">
              {plan.priorArt.matches.map((m, i) => (
                <div key={i} className="text-sm text-[var(--text-secondary)]">
                  <a href={m.url} target="_blank" rel="noopener noreferrer"
                    className="font-medium text-amber-400 hover:underline flex items-center gap-1 w-fit">
                    {m.title} <ExternalLink size={10} />
                  </a>
                  <p>{m.summary}</p>
                </div>
              ))}
            </div>
          </div>
        </div>
      )}

      {plan.redirectSuggestion.show && plan.redirectSuggestion.message && (
        <div className="flex gap-3 p-4 rounded-xl border border-blue-500/20 bg-blue-500/5 fade-up-1">
          <Info size={16} className="text-blue-400 shrink-0 mt-0.5" />
          <p className="text-sm text-[var(--text-secondary)]">
            {plan.redirectSuggestion.message}
            {plan.redirectSuggestion.url && (
              <a href={plan.redirectSuggestion.url} target="_blank" rel="noopener noreferrer"
                className="ml-2 text-blue-400 hover:underline inline-flex items-center gap-1">
                View <ExternalLink size={10} />
              </a>
            )}
          </p>
        </div>
      )}

      {/* Feedback */}
      {showFb && (
        <div className="panel panel-accent rounded-xl p-5 space-y-3 fade-up">
          <p className="text-sm text-[var(--text-secondary)] font-medium">Describe what to change (optional)</p>
          <textarea value={feedback} onChange={e => setFeedback(e.target.value)}
            placeholder="e.g. Add a caching layer, split the API into microservices…"
            className="input-base h-20 resize-none" />
          <div className="flex gap-2 justify-end">
            <button onClick={() => setShowFb(false)} className="btn-secondary px-3 py-1.5 text-sm">Cancel</button>
            <button onClick={handleRegenerate} disabled={regen}
              className="btn-primary px-4 py-1.5 text-sm">
              {regen && <RefreshCw size={12} className="animate-spin" />}
              Regenerate
            </button>
          </div>
        </div>
      )}

      {/* View toggle + zoom */}
      <div className="space-y-3 fade-up-1">
        <div className="flex items-center gap-3">
          <p className="text-[10px] text-[var(--text-muted)] uppercase tracking-widest flex-1">Mermaid Diagram</p>
          <div className="flex items-center gap-1 bg-[var(--bg-elevated)] border border-[var(--border)] rounded-lg p-0.5">
            {['Preview', 'Edit'].map(mode => (
              <button key={mode} onClick={() => setEditMode(mode === 'Edit')}
                className={cn('px-3 py-1 rounded-md text-xs font-medium transition-all',
                  (editMode ? mode === 'Edit' : mode === 'Preview')
                    ? 'bg-[var(--text-primary)] text-[var(--bg)]'
                    : 'text-[var(--text-muted)] hover:text-[var(--text-primary)]')}>
                {mode}
              </button>
            ))}
          </div>
          <div className="flex items-center gap-1">
            <button onClick={() => setZoom(z => Math.max(0.5, z - 0.15))}
              className="p-1.5 rounded-lg bg-[var(--bg-elevated)] border border-[var(--border)]
                hover:border-[var(--border-accent)] text-[var(--text-muted)] hover:text-[var(--text-primary)] transition-all">
              <ZoomOut size={12} />
            </button>
            <span className="text-[10px] text-[var(--text-muted)] font-mono w-10 text-center">{Math.round(zoom * 100)}%</span>
            <button onClick={() => setZoom(z => Math.min(2, z + 0.15))}
              className="p-1.5 rounded-lg bg-[var(--bg-elevated)] border border-[var(--border)]
                hover:border-[var(--border-accent)] text-[var(--text-muted)] hover:text-[var(--text-primary)] transition-all">
              <ZoomIn size={12} />
            </button>
            <button onClick={() => setZoom(1)}
              className="px-2 py-1 text-[10px] rounded-lg bg-[var(--bg-elevated)] border border-[var(--border)]
                hover:border-[var(--border-accent)] text-[var(--text-muted)] hover:text-[var(--text-primary)] transition-all">
              Reset
            </button>
          </div>
        </div>

        <div className={cn('flex gap-3', editMode ? 'flex-row' : 'flex-col')}>
          {editMode && (
            <div className="flex-1 flex flex-col">
              <textarea
                value={rawSyntax}
                onChange={e => setRawSyntax(e.target.value)}
                spellCheck={false}
                className={cn(
                  'flex-1 min-h-[360px] input-base font-mono text-xs resize-none leading-relaxed',
                  syntaxError ? 'border-[var(--danger)]/40' : ''
                )}
              />
              {syntaxError && (
                <p className="text-xs text-[var(--danger)] mt-2 flex items-center gap-1.5">
                  <AlertTriangle size={11} /> {syntaxError}
                </p>
              )}
            </div>
          )}

          <div className={cn('panel rounded-xl overflow-hidden', editMode ? 'flex-1' : 'w-full')}>
            <div className="overflow-auto min-h-[300px] max-h-[520px] flex items-center justify-center p-6 bg-[var(--bg)]/60">
              <div
                ref={mermaidRef}
                className="mermaid-wrap"
                style={{ transform: `scale(${zoom})`, transformOrigin: 'top center', transition: 'transform 0.2s' }}
              />
              {syntaxError && !editMode && (
                <div className="text-[var(--text-muted)] text-sm text-center">
                  <AlertTriangle size={20} className="mx-auto mb-2 text-[var(--danger)]/50" />
                  Diagram has a syntax error. Use Edit mode to fix it.
                </div>
              )}
            </div>
          </div>
        </div>
      </div>

      {/* Time budget */}
      <div className="grid grid-cols-2 md:grid-cols-4 gap-3 fade-up-2">
        {[
          { label: 'Total Hours',   value: `${plan.timeBudget.total_hours}h` },
          { label: 'Working Hours', value: `${plan.timeBudget.working_hours}h` },
          { label: 'MVP Cap',       value: `${plan.timeBudget.core_mvp_hours_cap}h` },
          { label: 'Deadline',      value: plan.timeBudget.deadline_note ? 'Set' : 'TBD' },
        ].map(item => (
          <div key={item.label} className="panel rounded-xl p-4 text-center">
            <p className="text-xl font-black text-[var(--text-primary)]">{item.value}</p>
            <p className="text-[11px] text-[var(--text-muted)] mt-1 uppercase tracking-wider">{item.label}</p>
          </div>
        ))}
      </div>

      {plan.timeBudget.deadline_note && (
        <p className="text-sm text-[var(--text-muted)] panel rounded-xl px-4 py-3 fade-up-2">
          ⏱ {plan.timeBudget.deadline_note}
        </p>
      )}

      {plan.notes && (
        <div className="panel rounded-xl px-4 py-4 fade-up-3">
          <p className="text-[10px] text-[var(--text-muted)] uppercase tracking-wider mb-1.5">Agent Notes</p>
          <p className="text-sm text-[var(--text-secondary)] leading-relaxed">{plan.notes}</p>
        </div>
      )}
    </div>
  );
}
